services:
  container1:
    image: image_container1
    container_name: container1
    ports:
      - 6000:6000
    networks:
      - docker-spring
    volumes:
      - .:/app

  container2:
    image: image_container2
    container_name: container2
    ports:
      - 6001:6001
    networks:
      - docker-spring
    volumes:
      - .:/app

networks:
  docker-spring:
    driver: bridge
